### ISSUE TITLE
Error in BestMatchParams

### ISSUE THREAD

**Issue by lazappi** [YosefLab/SymSim#1]
Hi

I think SymSim is a really cool model for scRNA-seq data and I have been trying to give it a go but I run into the following error when I try to use `BestMatchParams`

```r
library(SymSim)

counts <- matrix(rpois(100 * 1000, 10), nrow = 1000, ncol = 100)
params <- SymSim:::BestMatchParams("UMI", counts)

# Error in file(file, "rt") : cannot open the connection
# In addition: Warning message:
# In file(file, "rt") 
```

I think this is because the files are read using `read.table` instead of loading them using `data`. I would really like to give your package a go so it would be great if we can come up with a fix.

(P.S. I had to use `SymSim:::BestMatchParams` to access the function because it doesn't seem to be exported in the NAMESPACE file)

**Comment by xiuweiz** [comment]
Hi Luke,
Sorry for my late reply. I just got back from vacation back to my usual routine. 
I used txt files to store the measures (mean, sd and percent nonzero) because the corresponding RData files are much larger than the txt files. I will look into it in a bit and let you know. 
Xiuwei

**Comment by xiuweiz** [comment]
Hi Luke,

I was able to run BestMatchParams (without using SymSim:::) from a newly installed R version if I do 

```
library("devtools")
load_all("SymSim")
```
to load SymSim instead of using `library(SymSim)`. Did you load SymSim with devtools? 

Can you see which files are not found when you met the error of "cannot open the connection"? 
Thanks!

**Comment by lazappi** [comment]
Hi @xiuweiz 

`devtools::load_all()` is designed to be used by package developers not users of a package. The standard way to install and use an R package is to install it `install.packages("pkg_name")` (or `devtools::install_github("pkg_name")` and then load it using `library(pkg_name)`. Having to use `devtools::load_all()` makes it pretty difficult and inconvenient to use SymSim, which is unfortunate because I think it's a great model.

For example it means users can't use the normal R package infrastructure, need to download the source and need to do their analysis in the SymSim folder. It also means that SymSim can't be hosted on CRAN or Bioconductor (if that is something you wanted to do in the future.

It would be great if SymSim could be adapted so it can be used in a more familiar way but I understand if you don't have the time to do that at the moment.

**Comment by xiuweiz** [comment]
Thank you very much Luke for your suggestion. Yes we do plan to improve the package and submit to CRAN or Bioconductor. I'll try to do it within the next two weeks.

**Comment by beyondpie** [comment]
@lazappi 
I agree with you that SymSim is a great model, but not easy to use (codes are not organized that well like splatter... )
