### ISSUE TITLE
Dividebatches has repeat names on batch ? 

### ISSUE THREAD

**Issue by beyondpie** [YosefLab/SymSim#10]
@xiuweiz 
Hi, thank you for your functions!
After I use it to generate the samples.  I got the erros blow when trying to plot it.
Is this my code bug ? 

I use nbatch equals to 10.  And  the column 35 and 36 of `observed_counts_2batches$cell_meta`   have the same name "batch", but the values are different. The column 35 are all ones; while the column 36 are from one to ten, which should be the batch.

------------- 
Error: `data` must be uniquely named but has duplicate columns
Run `rlang::last_error()` to see where the error occurred.
> names(tsne_UMI_batches[[2]])
[1] "data"        "layers"      "scales"      "mapping"     "theme"      
[6] "coordinates" "facet"       "plot_env"    "labels"     
> names(tsne_UMI_batches[[2]]$data)
 [1] "cellid"           "pop"              "kon_nonDE_evf1"   "kon_nonDE_evf2"  
 [5] "kon_nonDE_evf3"   "kon_nonDE_evf4"   "kon_nonDE_evf5"   "kon_nonDE_evf6"  
 [9] "kon_nonDE_evf7"   "kon_nonDE_evf8"   "kon_nonDE_evf9"   "kon_nonDE_evf10" 
[13] "koff_nonDE_evf1"  "koff_nonDE_evf2"  "koff_nonDE_evf3"  "koff_nonDE_evf4" 
[17] "koff_nonDE_evf5"  "koff_nonDE_evf6"  "koff_nonDE_evf7"  "koff_nonDE_evf8" 
[21] "koff_nonDE_evf9"  "koff_nonDE_evf10" "s_nonDE_evf1"     "s_DE_evf2"       
[25] "s_DE_evf3"        "s_DE_evf4"        "s_DE_evf5"        "s_DE_evf6"       
[29] "s_DE_evf7"        "s_DE_evf8"        "s_DE_evf9"        "s_DE_evf10"      
[33] "alpha"            "depth"            "batch"            "batch"           
[37] "label"            "x"                "y"               
>

**Comment by xiuweiz** [comment]
It looks like that the batch attribute is added twice, but in the code I found it's added only once now in the DivideBatches function. Are you using the latest version?

**Comment by beyondpie** [comment]
Thanks, I will check it later since I am now simulating one individual and with/without gene module situation. 

BTW,  I found two possible bugs:
SimulateTrueCounts function: 
a. geffect_mean, vary  shown in “usage” are not shown in “argument”
b. param_realdata = "zeisel.imputed" has two options in “argument”, 
    while only has one option in the code. Also the second optional dataset is not clear for what is means.

**Comment by beyondpie** [comment]
I have one problem when I want to simulate UMI and nonUMI experiments. 
Can you help me on how to choose the corresponding parameters directly for these two experiments? From Table 2 in your paper, lots of parameters for me, and not sure how to choose them would be OK.

**Comment by xiuweiz** [comment]
> Thanks, I will check it later since I am now simulating one individual and with/without gene module situation.
> 
> BTW, I found two possible bugs:
> SimulateTrueCounts function:
> a. geffect_mean, vary shown in “usage” is not shown in “argument”
> b. param_realdata = "zeisel.imputed" has two options in “argument”,
> while only has one option in the code. Also, the second optional dataset is not clear for what is means.

Thanks, I've updated these.
The two options of param_realdata are actually zeisel.imputed or null. Null means not using any distribution learned from real data, and this is often not preferred. I have removed the choice of the other real dataset zeisel.pop4 as it's similar to zeisel.imputed.

**Comment by xiuweiz** [comment]
> I have one problem when I want to simulate UMI and nonUMI experiments.
> Can you help me on how to choose the corresponding parameters directly for these two experiments? From Table 2 in your paper, lots of parameters for me, and not sure how to choose them would be OK.
> 
> According to the SimulateTrueCounts source code, I know that param_realdata is used to estimate genes' k_on, k_off, and s. Though "zeisel.imputed" are from UMI-based experiments, I could still use it for nonUMI simulation, right? Since UMI and nonUMI should be different only on simulating the observed counts from the true counts.

You can use the default values for some of the parameters, and the ones you need to set are roughly the ones which are set in the vignette examples. For True2Observed counts the main parameters are alpha_mean and depth_mean. alpha_mean is the capture efficiency, and the values set in the vignette are perhaps lower than the actual mRNA capture efficiency with today's technology. You may set it as 0.1~0.3 for UMI and 0.2~0.4 for nonUMI (to be confirmed with the most up-to-date knowledge on the current technology). depth_mean is sequencing depth, which is a value users choose when sending libraries for sequencing. 

Since you are simulating multiple cell types, you may want the clusters are separated according to your own preference. As you can see from the examples in the paper, when the input tree is fixed, you can change Sigma to get very well separated clusters or less well separated clusters. Also, increasing n_de_evfs can also make the clusters more distinct as they represent the number of biological conditions that cause differences between cell types. 

The current BestMatchParams() function is only for the case of simulating one single population. In the case of multiple populations, you can plot the tsne/umap plot and adjust sigma and n_de_evfs to make the clusters look like what you want. This also depends on the structure and edge lengths of the input tree. When using the tree shown in the paper you can see the difference in setting sigma to be 0.4 and 0.7. 

Yes you can use "zeisel.imputed"  for both UMI and nonUMI simulations.

**Comment by beyondpie** [comment]
@xiuweiz 
Thank you for your reply! 
BTW, for `PlotTsne`, there is no "pop" for observed counts meta (should be 'cell_meta.pop'); however for true_counts, there is "pop" field for meta.
In vignette, only "pop" is mentioned.

If nbatch equals to 1, should I ignore add batch effect or should add one batch effect ?

**Comment by xiuweiz** [comment]
Can you show how your observed_counts$cell_meta looks like? From my output I do see the pop field. 

If you want only 1 batch you can just skip the function DivideBatches. That will not add batch effect.

**Comment by beyondpie** [comment]
```
> str(obs_umi$cell_meta)
'data.frame':	300 obs. of  35 variables:
 $ cell_meta.cellid          : chr  "cell_1" "cell_2" "cell_3" "cell_4" ...
 $ cell_meta.pop             : int  1 1 1 1 1 1 1 1 1 1 ...
 $ cell_meta.kon_nonDE_evf1  : num  0.774 1.109 0.987 0.783 1.284 ...
 $ cell_meta.kon_nonDE_evf2  : num  0.885 1.056 1.326 1.071 0.906 ...
 $ cell_meta.kon_nonDE_evf3  : num  1.269 0.919 0.897 0.936 0.615 ...
 $ cell_meta.kon_nonDE_evf4  : num  0.919 1.132 0.975 1.441 1.133 ...
 $ cell_meta.kon_nonDE_evf5  : num  0.739 0.793 1.186 1.206 0.948 ...
 $ cell_meta.kon_nonDE_evf6  : num  1.062 1.149 0.976 0.906 1.098 ...
 $ cell_meta.kon_nonDE_evf7  : num  0.945 0.864 1.344 0.73 0.805 ...
 $ cell_meta.kon_nonDE_evf8  : num  1.106 0.935 0.988 0.893 0.956 ...
 $ cell_meta.kon_nonDE_evf9  : num  1.243 0.996 1.017 0.921 1.254 ...
 $ cell_meta.kon_nonDE_evf10 : num  0.881 0.898 1.009 0.729 1.185 ...
 $ cell_meta.koff_nonDE_evf1 : num  1.171 0.82 0.897 1.136 0.749 ...
 $ cell_meta.koff_nonDE_evf2 : num  1.308 0.7 0.693 0.858 0.721 ...
 $ cell_meta.koff_nonDE_evf3 : num  0.539 1.042 1.026 1.01 0.851 ...
 $ cell_meta.koff_nonDE_evf4 : num  0.922 1.011 0.863 0.892 0.782 ...
 $ cell_meta.koff_nonDE_evf5 : num  1.303 0.868 0.819 0.912 0.852 ...
 $ cell_meta.koff_nonDE_evf6 : num  1.294 1.057 0.759 1.127 0.832 ...
 $ cell_meta.koff_nonDE_evf7 : num  0.569 0.998 0.808 1.263 0.821 ...
 $ cell_meta.koff_nonDE_evf8 : num  1.02 0.88 1.105 0.982 1.01 ...
 $ cell_meta.koff_nonDE_evf9 : num  1.338 1.14 0.76 0.958 1.19 
```

This is the observed counts for UMI-based experiment.

**Comment by beyondpie** [comment]
> Can you show how your observed_counts$cell_meta looks like? From my output I do see the pop field.
> 
> If you want only 1 batch you can just skip the function DivideBatches. That will not add batch effect.

The question I actually concern is that if I should add batch effect even I have one batch? From the source codes,  it looks like that the batch effect will append to the genes for all the cells in that batch with the same effect (but different between genes due to randomness)? If so, maybe I should simulate the batch effect so that the genes have more randomness among them even in one batch ?

**Comment by xiuweiz** [comment]
You are right, the batch effect is gene-specific and batch specific. Yes I think it's realistic to add batch effect even if there is just one batch.
