### ISSUE TITLE
Error in SimulateTrueCounts()

### ISSUE THREAD

**Issue by aarzalluz** [YosefLab/SymSim#13]
Hi @xiuweiz,

Congratulations on SymSim! It's a really good model for single-cell RNA-Seq simulation, and I would really like to try it out.

I took a deep look at your paper to make sense of the different parameters of the `SimulateTrueCounts()` and `True2ObservedCounts()`, because even though they're somewhat intuitive, there's many of them and they're not described in the documentation -which would be a great addition, if I may make a suggestion to improve the package. However, I'm running into an error when running `SimulateTrueCounts()`:

I run the function with the following parameters:

```
true_counts <- SimulateTrueCounts(ncells_total = 300, min_popsize = 50, ngenes = 8000, 
                                  nevf = 10, evf_type = "discrete", n_de_evf = 9, 
                                  vary = "s", Sigma = 0.4,
                                  gene_effect_prob = 0.5, bimod = 0.5, 
                                  prop_hge = 0.03, mean_hge = 4,
                                  randseed = 123)
``` 

and get the following error:

```
Error in sample.int(length(x), size, replace, prob) : 
  cannot take a sample larger than the population when 'replace = FALSE'
```

I tried changing/removing parameters to trace the error back. Funnily enough, the error only disappears when I switch to `evf_type = "one.population"`. If I do that and leave all other parameters with the same values, the simulation seems to work fine. I found a couple of places in your code where `sample()` is run with `replace = FALSE` (lines 459 and 598 in the `simulation_functions.R` file), but didn't do any further research. 

Do you have any idea how this could be solved?

Thanks,

Ángeles

**Comment by xiuweiz** [comment]
Hi Ángeles,
Thanks for using SymSim. By setting evf_type to "discrete" you are asking to generate multiple populations (clusters), and that requires you to input a tree which represent how many clusters you want, and the relationship between clusters. We provide two trees, Phyla3() and Phyla5(), which generates respectively 3 and 5 clusters. It's likely that the error you got is because the tree is not provided to the phyla argument and the default is NULL. So errors occur when we assign the number of cells for each cluster. 
-Xiuwei

**Comment by aarzalluz** [comment]
Hi @xiuweiz,

Thanks! From reading the vignette, I understood that setting `phyla = NULL` just would generate the tree randomly, and assumed it would otherwise throw a warning if a tree was mandatory (i.e. from `SimulateTrueCounts()` help page, the phyla argument line reads: `Can either be generated randomly or read from newick format file using the ape package`).  Perhaps that argument should be empty by default in the function and throw an explicit error if no value is provided? I also found confusing that there was no mention to the `Phyla3()` and `Phyla5()` functions in the help page, even though it is briefly referred to in the vignette.

If you require no particular structure or relationsihp between the clusters, how could a random tree be generated? Can it be done with SymSim?

Thanks,

Ángeles

**Comment by beyondpie** [comment]
@aarzalluz 
Just a suggestion:  I face a simular problem before. And I figure out my input issue on phyla based on `traceback()` in R, and using debug tool in R. They are simple to use and you can track the data stream in the function.

**Comment by xiuweiz** [comment]
> Hi @xiuweiz,
> 
> Thanks! From reading the vignette, I understood that setting `phyla = NULL` just would generate the tree randomly, and assumed it would otherwise throw a warning if a tree was mandatory (i.e. from `SimulateTrueCounts()` help page, the phyla argument line reads: `Can either be generated randomly or read from newick format file using the ape package`). Perhaps that argument should be empty by default in the function and throw an explicit error if no value is provided? I also found confusing that there was no mention to the `Phyla3()` and `Phyla5()` functions in the help page, even though it is briefly referred to in the vignette.
> 
> If you require no particular structure or relationsihp between the clusters, how could a random tree be generated? Can it be done with SymSim?
> 
> Thanks,
> 
> Ángeles

Yes one can generate a random tree with function tree<-pbtree(n) from the phytools package. n is the number of clusters. You can view the tree with plot(tree). Yes it's a good idea to report an error when the tree is not given in the mode of multiple cell types.

**Comment by xiuweiz** [comment]
I've removed the default phyla=NULL and updated explanation of phyla argument.
