### ISSUE TITLE
getDEgenes returns non adjusted p-value

### ISSUE THREAD

**Issue by beyondpie** [YosefLab/SymSim#14]
@xiuweiz 

According to the document about `getDEgenes`, it should return the adjusted Wilcoxon p-value, but from the source code below:

```
 wil.p_true_counts <- sapply(1:ngenes, function(igene) 
    return(wilcox.test(true_counts_norm[igene, popA_idx], true_counts_norm[igene, popB_idx])$p.value))
  
  wil.adjp_true_counts <- p.adjust(wil.p_true_counts, method = 'fdr')
return(list(nDiffEVF=n_useDEevf, logFC_theoretical=logFC_theoretical, wil.p_true_counts=wil.p_true_counts))
}
```

**Comment by beyondpie** [comment]
Besides that, how to get the mean expression level of one gene in one population?  

```
logFC_theoretical <- sapply(1:ngenes, function(igene)
    return( log2(mean(s_mat[igene, popA_idx]*kon_mat[igene, popA_idx]/(kon_mat[igene, popA_idx]+koff_mat[igene, popA_idx]))/
                   mean(s_mat[igene, popB_idx]*kon_mat[igene, popB_idx]/(kon_mat[igene, popB_idx]+koff_mat[igene, popB_idx])) ) ))
```

from the source code above in getDEgenes,  dost that mean:
```
mean(s_mat[igene, popA_idx]*kon_mat[igene, popA_idx]/(kon_mat[igene, popA_idx]+koff_mat[igene, popA_idx]))
```
 is the average expression level for gene "igene" in the population "popA_idx"?  If I want to get the expression level on each cell, then I don't need the `mean` right?

**Comment by xiuweiz** [comment]
> Besides that, how to get the mean expression level of one gene in one population?
> 
> ```
> logFC_theoretical <- sapply(1:ngenes, function(igene)
>     return( log2(mean(s_mat[igene, popA_idx]*kon_mat[igene, popA_idx]/(kon_mat[igene, popA_idx]+koff_mat[igene, popA_idx]))/
>                    mean(s_mat[igene, popB_idx]*kon_mat[igene, popB_idx]/(kon_mat[igene, popB_idx]+koff_mat[igene, popB_idx])) ) ))
> ```
> 
> from the source code above in getDEgenes, dost that mean:
> 
> ```
> mean(s_mat[igene, popA_idx]*kon_mat[igene, popA_idx]/(kon_mat[igene, popA_idx]+koff_mat[igene, popA_idx]))
> ```
> 
> is the average expression level for gene "igene" in the population "popA_idx"? If I want to get the expression level on each cell, then I don't need the `mean`, right?

That's correct. 

Also regarding the adjusted p-value vs. non-adjusted p-value:
we found that if we use adjusted p-value there are a lot of NAs in the output of some methods (like DESeq2). So we used the p-value instead, because the p-value and adjusted p-value order the genes in the same way, and what we evaluate here is the order of genes not the actual p-values.
