### ISSUE TITLE
how to use PlotCoutHeatmap

### ISSUE THREAD

**Issue by beyondpie** [YosefLab/SymSim#16]
@xiuweiz 
I want to use this function to show the simulation results.

```Plotting logged expression distribution
Description
takes an expression matrix and makes a 2D histogram on the log scale where each row is a gene and the number of samples in a bin is shown by the intensity of the color

Usage
PlotCountHeatmap(
  log_real,
  mean_counts,
  given_ord = NA,
  zeropropthres = 0.8,
  filename,
  saving = F,
  data_name
)


log_real | the logged distribution of count distribution
mean_counts | the average expression for each gene, used for sorting purpose


```
What's the meaning of a logged distribution of count distribution?  I can get true counts and observed counts, but what's the log_real mean ?

For mean_counts, I can get the average gene expression on each cell by the kinetic parameters from true_counts as followed based on your `getDEgenes` function.

```
get_mean_counts <- function(kinetic_params) {
    kon <- kinetic_params[[1]]
    koff <- kinetic_params[[2]]
    s <- kinetic_params[[3]]
    return(s * kon / (kon + koff))
}

```

**Comment by beyondpie** [comment]
BTW,  in the function `getDEgenes`,  `log_real, mean_counts, filename, data_name` need to be set by users, but they are not put in the first lines of the arguments, which makes users might ignore the need for setting `filename, dataname` since they are between the parameters having the default settings. 

I also notice the same "issue" (maybe not an issue from your point of view) in the function of `True2ObservedCounts` and `SimulateTrueCounts`.  They have the parameters need to be set at the last, which is really hard to see at first.

**Comment by xiuweiz** [comment]
> @xiuweiz
> I want to use this function to show the simulation results.
> 
> ```
> Description
> takes an expression matrix and makes a 2D histogram on the log scale where each row is a gene and the number of samples in a bin is shown by the intensity of the color
> 
> Usage
> PlotCountHeatmap(
>   log_real,
>   mean_counts,
>   given_ord = NA,
>   zeropropthres = 0.8,
>   filename,
>   saving = F,
>   data_name
> )
> 
> 
> log_real | the logged distribution of count distribution
> mean_counts | the average expression for each gene, used for sorting purpose
> ```
> 
> What's the meaning of a logged distribution of count distribution? I can get true counts and observed counts, but what's the log_real mean ?
> 
> For mean_counts, I can get the average gene expression on each cell by the kinetic parameters from true_counts as followed based on your `getDEgenes` function.
> 
> ```
> get_mean_counts <- function(kinetic_params) {
>     kon <- kinetic_params[[1]]
>     koff <- kinetic_params[[2]]
>     s <- kinetic_params[[3]]
>     return(s * kon / (kon + koff))
> }
> ```

log_real is obtained through the function LogDist which is in summary_functions.R and should be working now. It converts the counts to log scale and bin the counts to get a distribution (like a histogram). An example of using the PlotCountHeatmap function is:
`heatmapplot <- PlotCountHeatmap(LogDist(countmatrix,seq(0,4,0.4)),rowMeans(countmatrix),
 given_ord= NA,zeropropthres=1,filename=NA,data_name='true counts',saving=F)
heatmapplot[[2]]`

**Comment by beyondpie** [comment]
Note: `LogDist` is not exported.

**Comment by beyondpie** [comment]
> For mean_counts, I can get the average gene expression on each cell by the kinetic parameters from true_counts as followed based on your getDEgenes function.
```
get_mean_counts <- function(kinetic_params) {
    kon <- kinetic_params[[1]]
    koff <- kinetic_params[[2]]
    s <- kinetic_params[[3]]
    return(s * kon / (kon + koff))
}
```

Is this reasonable?

**Comment by beyondpie** [comment]
In the meanwhile, I want to compare different imputation methods. One criteria could be the mean square error between the log true counts and log observed counts after imputation. Do you think this is reasonable?  The only issue, in my view, is that the log observed counts are after PCR and sequencing, which might be a little far away from true counts.

**Comment by xiuweiz** [comment]
> > For mean_counts, I can get the average gene expression on each cell by the kinetic parameters from true_counts as followed based on your getDEgenes function.
> 
> ```
> get_mean_counts <- function(kinetic_params) {
>     kon <- kinetic_params[[1]]
>     koff <- kinetic_params[[2]]
>     s <- kinetic_params[[3]]
>     return(s * kon / (kon + koff))
> }
> ```
> 
> Is this reasonable?

As you want to visualize a count matrix, you just need to calculate mean with RowMeans of your count matrix. get_mean_counts() returns a theoretical mean based on the kinetic parameter, which is not affected by the intrinsic noise from transcription burst.

**Comment by xiuweiz** [comment]
> In the meanwhile, I want to compare different imputation methods. One criteria could be the mean square error between the log true counts and log observed counts after imputation. Do you think this is reasonable? The only issue, in my view, is that the log observed counts are after PCR and sequencing, which might be a little far away from true counts.
> 
> Since imputations are focus on technique drop out. Do you know how I can know the observed counts without dropout-like technique issue?

I am not sure how to quantify accuracy of imputation methods - comparing two matrices either with or without log transform sounds a bit "overkilling". Sorry I dont have any quick suggestions for this one. 

To get data without dropout, you can set alpha_mean to 1 for the True2ObservedCounts function. A faster alternative would be to simply perform subsampling on the true counts with a certain probability (mRNA capture efficiency). In this case the difference between the resulting data and the true counts is only dropouts, although this is not complete the same as setting alpha_mean=1 (or a high value like 0.9 and a very small alpha_sd) as the latter way gives other bias. However, in the observed counts, most technical noise comes from dropouts.

**Comment by xiuweiz** [comment]
I didn't expect that one might set a very high alpha_mean so if you do set it to be 1 there may be a bug saying you have a probability larger than 1.  I just set a limit on the probability to take this into account.
