### ISSUE TITLE
error in estimating params from real data

### ISSUE THREAD

**Issue by xianingz** [YosefLab/SymSim#19]
When I run the BestMatchParams command I met the error as follows:
`> best_matches_UMI <- BestMatchParams('UMI',dge,'best_params.umi.qqplot.pdf')`
no non-missing arguments to min; returning Infno non-missing arguments to max; returning -InfError in plot.window(...) : need finite 'xlim' values

dge is a count matrix with gene as rows and cells as columns. I tried the example and that one works. I tried to set the depth_range parameter but still get this error (and I couldn't find anywhere the explanations for the depth_range parameter).

**Comment by xiuweiz** [comment]
Hi, how does the distribution of the three statistical features (mean of genes, standard deviation of genes, percentage of non-zero of genes) look like? 
If you do 
```
mean_exprs <- quantile(rowMeans(counts+1,na.rm=T),seq(0,1,0.002))
sd_exprs <- quantile(apply(counts,1,sd),seq(0,1,0.002),na.rm=T)
percent0 <- quantile(apply(counts,1,percent_nonzero),seq(0,1,0.002))
```

by replacing counts by your dge, do you get any NA or Inf values in any of the vectors mean_exprs, sd_exprs and percent0?

**Comment by xianingz** [comment]
Thanks for the quick reply, I checked as you suggested
`
counts = dge
mean_exprs <- quantile(rowMeans(counts+1,na.rm=T),seq(0,1,0.002))
sd_exprs <- quantile(apply(counts,1,sd),seq(0,1,0.002),na.rm=T)
percent0 <- quantile(apply(counts,1,percent_nonzero),seq(0,1,0.002))

sum(!is.finite(mean_exprs))
sum(!is.finite(sd_exprs))
sum(!is.finite(percent0))
`
All return zero, so I don't think there is any NA or Inf values.

**Comment by xiuweiz** [comment]
I don't have a good guess of what went wrong with the current information. I ran the function on some other generated count matrix and it worked. I'm happy to test your particular case if you don't mind sharing the mean_exprs, sd_exprs, and percent0 variables. Or, as you have calculated these three variables mean_exprs, sd_exprs, and percent0 you can look into the code of the function BestMatchParams() and run it line by line to see where the problem occurs.

**Comment by xianingz** [comment]
I found out the reason. I have some genes with all zeros in my matrix, which creates zeros in sd_exprs. And then log10(sd_exprs) generated -Inf values.

**Comment by xiuweiz** [comment]
Thanks for letting me know!
