### ISSUE TITLE
Not all files in data directory are available

### ISSUE THREAD

**Issue by agdenadel** [YosefLab/SymSim#2]
I just installed SymSim using `devtools::install_github` as described in the README. When I tried to follow the vignette I get the following error

```
  cannot open compressed file 'SymSim/data/param_realdata.zeisel.imputed.robj', probable reason 'No such file or directory'
```

When I check the datasets available in the package using 

`data(package='SymSim')`

I get the following

```
`Data sets in package ‘SymSim’:

Newick_ABCDE                     
Newick_animals                   
cortex_counts                    
gene_len_pool                    
len2nfrag                        
len2prob3pri                     
ss2_130cells_counts (Th17_data)
                                 
ss2_130cells_tpm (Th17_data) `

```

**Comment by agdenadel** [comment]
In the meantime, reverting to cloning the repo and using `load_all` is a workaround, but I imagine this would need to be fixed for the package to go on CRAN or Bioconductor

**Comment by xiuweiz** [comment]
Hi, thanks for the feedback! We initially used load_all in the vignette but then just for users to be able to install it more easily we updated to install_github(). Thanks for pointing out the problem. I'll fix it over the next few days.

**Comment by xiuweiz** [comment]
Hi, thanks again for your comments. I believe this issue is now fixed and you can install by devtools::install_github() without cloning the repo to your local computer. Please let me know if you encounter further problems.
