### ISSUE TITLE
any specific reason to hard code min_module_size as 10 ?

### ISSUE THREAD

**Issue by beyondpie** [YosefLab/SymSim#21]
Hi 
I notice that the min_module_size is hardcoded as 10. I think I can change it to any reasonable number (such as 20). But wonder if there is any specific concern?  In the meanwhile, would you mind to explain a little about how the GeneEffects are changed when we use gene-module?

**Comment by xiuweiz** [comment]
There is no specific reason for setting min_module_size to be 10. I just didn't want to add too many parameters at once. 
The basic idea of implementing module genes is to set genes in the same module to have similar gene effects. First, these gene effect vectors should have the same positions which are non-zero values (we set most of the values in gene effects to be 0). Also, each gene module corresponds to a population, and I also did something to make these genes highly expressed in this population. The way that is implemented is: I selected the non-zero positions in gene-effect vectors for the genes to be the positions where the EVFs (of cells in the corresponding population) are largest for this set of genes overall. However, this doesn't lead to a clear pattern to show that these genes are more highly expressed in that population, as the EVF values are not very different from each other and other noise is introduced during other steps. But this is not a feature that must be there.

**Comment by beyondpie** [comment]
Hi @xiuweiz 
Thanks for your explanation! 
So currently, each cell population has one gene module.  Another way to think about gene modules would be each cell can have multiple gene modules, and different cell populations might have different expressions on the gene modules (not different gene module itself).   

Some gene modules are consistant across cell populations,  which means they are the critical and conservative genes (like cell cycle genes, I guess). 

Is that possible that one gene can participate in multiple gene modules? 

Do you have some idea to implement gene modules in this way? 

Thanks!
Songpeng

**Comment by xiuweiz** [comment]
Hi Songpeng,
Regardless of the correspondence between gene module and cell populations, I don't think it's a common scenario that a gene can participate in multiple gene modules. First, a set of genes form a gene module means that this set of genes coexpress. If we cluster the genes then each gene will have one cluster id. It's hard for me to imagine a gene being associated with more than one modules. Do you have an example of such cases?

Xiuwei

**Comment by beyondpie** [comment]
Hi Xiuwei,

Thanks for your comments. My understanding is that some genes may show a two-mode expression pattern, which makes them belong to two possible modules? 
BTW,  our paper about scRNASeq imputation has been accepted and published https://academic.oup.com/nargab/article/2/4/lqaa077/5912574. Thanks for your great help in the simulation part. We use your tools as one way for simulation! 
My email is  songpengzu@fas.harvard.edu, hope to see you in emails.

Thanks,
Songpeng
