### ISSUE TITLE
plot traces of mRNA counts for a gene in a cell over time

### ISSUE THREAD

**Issue by olechnwin** [YosefLab/SymSim#5]
Hi,

Thanks for creating this package. I'm planning to use this in many ways. 
I have generated true counts using `SimulateTrueCounts` and got the kinetic parameters for each gene. I am wondering whether it would be possible to plot the mRNA counts for a gene in a cell over time. I am trying to get a similar plot as in the following left panel image that I copied and pasted from [https://www.nature.com/articles/nbt.2642#Sec7](url)
![image](https://user-images.githubusercontent.com/20069067/71926815-1fe6d900-3162-11ea-8bc0-285b4c56b17a.png)

Thank you!

**Comment by xiuweiz** [comment]
Hi, thanks for your question. First, note that with this data, and with single cell RNA-Seq in general, we don't really have the expression level of a gene in one cell over time - we have the gene-expression data of one gene in different cells which can be sorted along the pseudotime.
To get such plots from SymSim, first you need to use the EVF_type="continuous" option to generate continuous populations. Then, in the results you get, you can find the cell meta data, where each cell has a branch it belongs to in the input tree, and on each branch, cells are ordered from early to late in the output. If you want to plot the expression levels of a gene from root to a leaf in the input tree, you can simply take all the branches of this lineage and concatenate the cells on these branches, and get the sequence of gene-expression levels of a given gene.
Please let me know if there is further questions.
