### ISSUE TITLE
build with vignettes failed

### ISSUE THREAD

**Issue by beyondpie** [YosefLab/SymSim#6]
Run `devtools::install_github("YosefLab/SymSim", ref="master", build_vignettes=TRUE)`, get the errors:
```
E  creating vignettes (36.6s)
   --- re-building ‘SymSimTutorial.Rmd’ using rmarkdown
   Quitting from lines 17-37 (SymSimTutorial.Rmd) 
   Error: processing vignette 'SymSimTutorial.Rmd' failed with diagnostics:
   cannot change working directory
   --- failed re-building ‘SymSimTutorial.Rmd’
   
   SUMMARY: processing the following file failed:
     ‘SymSimTutorial.Rmd’
   
   Error: Vignette re-building failed.
   Execution halted
Error: Failed to install 'SymSim' from GitHub:
  System command 'R' failed, exit status: 1, stdout + stderr (last 10 lines):
E> Quitting from lines 17-37 (SymSimTutorial.Rmd) 
E> Error: processing vignette 'SymSimTutorial.Rmd' failed with diagnostics:
E> cannot change working directory
E> --- failed re-building ‘SymSimTutorial.Rmd’
E> 
E> SUMMARY: processing the following file failed:
E>   ‘SymSimTutorial.Rmd’
E> 
E> Error: Vignette re-building failed.
E> Execution halted
```

**Comment by beyondpie** [comment]
Maybe this is my issue. I will test this later.

**Comment by xiuweiz** [comment]
Thanks. Please let me know if the problem persists.

**Comment by beyondpie** [comment]
Still get the same error. Even use force = T to build vignettes.  But this is not a big deal for me. I can read the Rmd directly.

**Comment by xiuweiz** [comment]
There is a line which tries to set the current directory and I have removed it as it's not necessary. It may work now.

**Comment by beyondpie** [comment]
> There is a line which tries to set the current directory and I have removed it as it's not necessary. It may work now.

Still errors at line 93-97. 

Error: Failed to install 'SymSim' from GitHub:
  System command 'R' failed, exit status: 1, stdout + stderr (last 10 lines):
E> Quitting from lines 93-97 (SymSimTutorial.Rmd) 
E> Error: processing vignette 'SymSimTutorial.Rmd' failed with diagnostics:
E> cannot open the connection
E> --- failed re-building ‘SymSimTutorial.Rmd’
E> 
E> SUMMARY: processing the following file failed:
E>   ‘SymSimTutorial.Rmd’
E> 
E> Error: Vignette re-building failed.
E> Execution halted

**Comment by beyondpie** [comment]
Also, suggest deleting the explanations about the two functions' parameters in vignette since we can get it from the help of the functions generated automatically by Roxygene.

**Comment by aarzalluz** [comment]
Hi,

Just wanted to add that I'm having a similar issue upon installation when trying to install the package using `devtools::install_github("YosefLab/SymSim", build_vignettes = TRUE)` -same error as @beyondpie when building the vignettes, but in lines 97-101:

```
Error: Failed to install 'SymSim' from GitHub:
  System command 'R' failed, exit status: 1, stdout + stderr (last 10 lines):
E> Quitting from lines 97-101 (SymSimTutorial.Rmd) 
E> Error: processing vignette 'SymSimTutorial.Rmd' failed with diagnostics:
E> cannot open the connection
E> --- failed re-building ‘SymSimTutorial.Rmd’
E> 
E> SUMMARY: processing the following file failed:
E>   ‘SymSimTutorial.Rmd’
E> 
E> Error: Vignette re-building failed.
E> Execution halted
```

Just so you know it's a generalized issue, but I can download+knit the .Rmd while it is solved.

Ángeles

**Comment by xiuweiz** [comment]
@beyondpie @aarzalluz 
The errors have to do with some data files used in the vignette which were not correctly linked to their paths. Th errors should be fixed now. Thanks for reporting the issues!
