### ISSUE TITLE
inconsistent help document

### ISSUE THREAD

**Issue by beyondpie** [YosefLab/SymSim#7]
Hi,
when I read the help document of the function `SimulateTrueCounts`, I find some parameters are not explained in the **Argument** (such as _impulse_) while some parameters in the Argument are not shown in the **Usage** (such as _gene_effect_sd, match_params_den_).

![help_doc](https://user-images.githubusercontent.com/6449478/83305781-63081e00-a1cf-11ea-98dc-935a6d27ca33.png)

**Comment by xiuweiz** [comment]
Thanks for the comments. Yes the help needs to be updated. I've updated the description for a few major functions and will update the rest over the next few weeks.

**Comment by beyondpie** [comment]
@xiuweiz 
I notice that you've updated the docs in .R files! 
BTW, remember to update the corresponding .Rmd files.  You can use `devtools::document()`.  R itself will not update the document even you click rebuild. 

Reference: 
http://r-pkgs.had.co.nz/man.html

**Comment by beyondpie** [comment]
Besides, maybe you can remove  all the .DS_Store files with `git rm `.

**Comment by xiuweiz** [comment]
Done, thanks!
