### ISSUE TITLE
getDEgenes function error: Error in lapply(X = X, FUN = FUN, ...) : object 'ngenes' not found

### ISSUE THREAD

**Issue by beyondpie** [YosefLab/SymSim#8]
Hi, 
when I try getDEgenes, I got the error as the title.
I notice that the input for getDEgenes are `function (true_counts_res, popA, popB) `, no extra parameter for ngenes.

**Comment by xiuweiz** [comment]
Thanks. ngenes is the total number of genes in the simulated data matrix. I added one line to get this number from true_counts_res in the getDEgenes function. The problem should be fixed now.
