### ISSUE TITLE
generating gene module

### ISSUE THREAD

**Issue by beyondpie** [YosefLab/SymSim#9]
@xiuweiz 
Thank you so much for your reply below!

> "gene effect" is the vector which controls behavior of genes. If you want to have gene modules where genes co-express, first these genes need to be controlled by the same EVFs. For example, if we say that evf1 and evf2 affect these genes, then in the gene-effect vectors of these genes, we need to make sure that the corresponding values are not zeros. Second, you may want these genes to co-express only in one cell type. In this case, we need to set evf1 and evf2 to be 0 for other cell types.
I don't think one can generate co-expressed gene modules directly by playing the arguments of the SimulateTrueCounts function. It'll require some altering of the evf and gene-effect vectors inside the function as I described above.
If you need to use the gene-module function and if you can wait (pls let me know more details: are you simulating discrete population or continuous population, how many co-expressed gene modules you want, and for each gene module does it exist in only one or two cell types ), I may be able to add that within two weeks.

> Also FYI another scRNA-seq simulator SERGIO can generate data guided by a regulatory network, so you should get co-express gene modules by designing the input network structure.

1. Actually I didn't figure out the differences between continuous and discrete populations ... Does this mean wheather the cell types are dependent on others (continuous) or not (discrete)?  I notice that you provide Phyla3 and Phyla5. So in order to generate more cell types, I can just follow your functions, and modify them into like Phyla8 and others, right? 

2. About co-expressed gene modules. 
I plan to simulate around five modules per cell.  I plan to let the different cells share the same gene modules. But they may show different expression patterns under different cell types.  According to your description above, I can modify evf (gene-effect vectors you mean: k_on, k_off, and s ? or just gene evf)  myself. 

Really glad to see that you can add the gene module support! But maybe I cannot wait for that long. I think I can have a test for this.

3. Thank you for letting me know SERGIO. I also notice that a similar R package:https://github.com/dynverse/dyngen. Do you know this?  I wonder if there exists some simple way to combine the two packages with yours to generate the gene module? If not, I will follow your advice to generate simple modules.

For example,  different genes' EVF may follow some multiple normal distributions, while the covariance matrix might follow some block-like structures. 
Like, gene a has the evf vector (v_1a, v_2a, ... ) gene b has the evf vector (v_1b, v_2b, ...). If a and b are in the same module, then (v_1a. v_1b) can sample from the same normal distribution or from a multiple normal distributions with strong correlations.  The same as (v_2a, v_2b), and so on. Do you think this is reasonable? 

Thank you very much!

**Comment by xiuweiz** [comment]
> @xiuweiz
> Thank you so much for your reply below!
> 
> > "gene effect" is the vector which controls behavior of genes. If you want to have gene modules where genes co-express, first these genes need to be controlled by the same EVFs. For example, if we say that evf1 and evf2 affect these genes, then in the gene-effect vectors of these genes, we need to make sure that the corresponding values are not zeros. Second, you may want these genes to co-express only in one cell type. In this case, we need to set evf1 and evf2 to be 0 for other cell types.
> > I don't think one can generate co-expressed gene modules directly by playing the arguments of the SimulateTrueCounts function. It'll require some altering of the evf and gene-effect vectors inside the function as I described above.
> > If you need to use the gene-module function and if you can wait (pls let me know more details: are you simulating discrete population or continuous population, how many co-expressed gene modules you want, and for each gene module does it exist in only one or two cell types ), I may be able to add that within two weeks.
> 
> > Also FYI another scRNA-seq simulator SERGIO can generate data guided by a regulatory network, so you should get co-express gene modules by designing the input network structure.
> 
> 1. Actually I didn't figure out the differences between continuous and discrete populations ... Does this mean wheather the cell types are dependent on others (continuous) or not (discrete)?  I notice that you provide Phyla3 and Phyla5. So in order to generate more cell types, I can just follow your functions, and modify them into like Phyla8 and others, right?
Yes. 

> 2. About co-expressed gene modules.
>    I plan to simulate around five modules per cell.  I plan to let the different cells share the same gene modules. But they may show different expression patterns under different cell types.  According to your description above, I can modify evf (gene-effect vectors you mean: k_on, k_off, and s ? or just gene evf)  myself.
> 
> Really glad to see that you can add the gene module support! But maybe I cannot wait for that long. I think I can have a test for this.
> 
> 1. Thank you for letting me know SERGIO. I also notice that a similar R package:https://github.com/dynverse/dyngen. Do you know this?  I wonder if there exists some simple way to combine the two packages with yours to generate the gene module? If not, I will follow your advice to generate simple modules.

Sorry, I don't easily see how to combine SERGIO/dyngen with SymSim. I'm aware of dyngen which is a more recent package, and can generate unspliced counts and RNA velocity.

> 
> For example, different genes' EVF may follow some multiple normal distributions, while the covariance matrix might follow some block-like structures.
> Like, gene a has the evf vector (v_1a, v_2a, ... ) gene b has the evf vector (v_1b, v_2b, ...). If a and b are in the same module, then (v_1a. v_1b) can sample from the same normal distribution or from a multiple normal distributions with strong correlations. The same as (v_2a, v_2b), and so on. Do you think this is reasonable?
> 
This might work. Please let me know how it goes.

> Thank you very much!

**Comment by beyondpie** [comment]
@xiuweiz 
Hi, have you tried to implement the gene modules later?  
I use real data recently, so haven't give the gene module a try.

**Comment by xiuweiz** [comment]
Yes I actually have implemented generating the gene modules, but it's with a different version of SymSim (on my local computer only). If you want to try it I'm happy to add it to this standard SymSim tomorrow.

**Comment by beyondpie** [comment]
Thank you!  If you can also add some document about how you handle the gene modules, that would be great!

**Comment by xiuweiz** [comment]
Will do. Working on testing the code. Will notify you when it's done and pushed.

**Comment by beyondpie** [comment]
Thank you very much!

**Comment by xiuweiz** [comment]
Changed pushed. Have not added this feature to the vignette. Some description is in Readme. Please let me know if you have questions.

**Comment by beyondpie** [comment]
Wonderful!  I can read your codes, so I think it's fine.
I will give it a try within this week~ 
Thank you very much!
Songpeng

**Comment by xiuweiz** [comment]
I will close this issue. Feel free to open another one if you experience any problem.
